[HPM] Proxy created: /  -> http://recognition:23121
[HPM] Proxy rewrite rule created: "^/api/recognition" ~> ""
[HPM] Proxy created: /  -> http://attention:23123
[HPM] Proxy rewrite rule created: "^/api/attention" ~> ""
[HPM] Proxy created: /  -> http://localization:23122
[HPM] Proxy rewrite rule created: "^/api/localization" ~> ""
[HPM] Proxy created: /  -> http://handraising:23124
[HPM] Proxy rewrite rule created: "^/api/handraising" ~> ""
node:events:485
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at Function.listen (/run/media/spectre/Elements/Projects/GraduationProject/Complete/Gateway/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/run/media/spectre/Elements/Projects/GraduationProject/Complete/Gateway/app.js:408:5)
    at Module._compile (node:internal/modules/cjs/loader:1734:14)
    at Object..js (node:internal/modules/cjs/loader:1899:10)
    at Module.load (node:internal/modules/cjs/loader:1469:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1973:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v23.9.0
